import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: '#4E525F',
    borderWidth: 1,
    borderRadius: 11,
    padding: 8,
    marginTop: 16,
    paddingHorizontal: 10,
  },
  iconWrapper: {
    backgroundColor: '#4E525F',
    padding: 13,
    borderRadius: 6,
    marginRight: 16,
  },
  projectName: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'Barlow-Regular',
  },
  textContent: {
    flex: 1,
  },
  auditTitle: {
    fontSize: 15,
    fontWeight: '500',
    fontFamily: 'Barlow-SemiBold',
  },
  dropdownIconWrapper: {
    backgroundColor: '#4E525F',
    borderRadius: '50%',
  },
  radioContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  outerCircle: {
    height: 24,
    width: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#444',
    alignItems: 'center',
    justifyContent: 'center',
  },
  innerCircle: {
    height: 12,
    width: 12,
    borderRadius: 10,
    backgroundColor: '#444',
  },
  radioLabel: {
    marginLeft: 8,
    fontSize: 16,
    marginRight: 24,
    fontFamily: 'Barlow-Regular',
  },
  headerSection: {
    backgroundColor: '#FFE9D6',
    padding: 12,
    paddingHorizontal: 8,
    borderRadius: 4,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    marginBottom: 16,
  },
  titleText: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'Barlow-Regular',
    marginBottom: 4,
  },
  subTitleText: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'Barlow-Regular',
  },
  authorText: {
    backgroundColor: '#4E525F',
    fontSize: 14,
    fontWeight: '500',
    paddingHorizontal: 8,
    paddingVertical: 2.5,
    color: '#fff',
    borderRadius: 32,
  },
  instructionsSection: {
    paddingTop: 8,
  },
  instructionText: {
    fontSize: 15,
    fontWeight: '400',
    fontFamily: 'Barlow-Regular',
    marginBottom: 8,
  },
  dateText: {
    fontSize: 10,
    fontWeight: '400',
    fontFamily: 'Barlow-Regular',
  },
  radioQuestionText: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'Barlow-Regular',
    paddingBottom: 16,
  },
  radioSection: {
    paddingHorizontal: 8,
    marginBottom: 16,
  },
  radioGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  section: {
    borderBottomWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'Barlow-Regular',
    marginBottom: 37,
  },
  label: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'Barlow-Regular',
  },
  input: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'Barlow-Regular',
    borderWidth: 0.5,
    borderColor: '#E0E3E7',
    padding: 12,
    borderRadius: 4,
    marginVertical: 10,
  },
  saveButton: {
    flexDirection: 'row',
    backgroundColor: '#24BC73',
    alignSelf: 'flex-end',
    padding: 16,
    marginTop: 34,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 4,
    borderRadius: 8,
    alignItems: 'center',
    gap: 12,
  },
  saveButtonText: {
    fontSize: 22,
    fontWeight: '500',
    fontFamily: 'Barlow-Regular',
    color: '#fff',
  },
  inputWrapper: {
    marginBottom: 12,
  },
  imageCon: {
    flexDirection: 'row',
  },
  photoButton: {
    backgroundColor: '#1FA163',
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
    gap: 8,
  },
  photoText: {
    fontFamily: 'Barlow-Regular',
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  fileNameContainer: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderRightWidth: 1,
    flex: 1,
    borderColor: '#ccc',
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
  },
  fileNameText: {
    fontFamily: 'Barlow-Regular',
  },
  containerDrop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderColor: '#5C5CE8',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: '#F7F9FC',
  },
  label: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'Barlow-Regular',
  },
  iconButton: {
    backgroundColor: '#444',
    borderRadius: '50%',
    padding: 8,
    paddingVertical: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionContainer: {
    paddingTop: 26,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#5C5CE8',
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    borderTopWidth: 0,
    marginBottom: 16,
  },
  row: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 30,
    alignItems: 'center',
  },
  imageContainer: {
    marginVertical: 15,
    position: 'relative',
  },
  image: {
    width: 80,
    height: 80,
    borderRadius: 8,
  },
  removeButton: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#ff4444',
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  removeButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  card: {
    padding: 16,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#FF9239',
    borderTopWidth: 0,
    borderBottomRightRadius: 11,
    borderBottomLeftRadius: 11,
  },
});
